/* tslint:disable */
/* eslint-disable */
/**
 * IM CXM APIs Documentation
 * IM CXM OpenApi description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * Adventure model
 * @export
 * @interface Adventure
 */
export interface Adventure {
    /**
     * 
     * @type {number}
     * @memberof Adventure
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Adventure
     */
    'region_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Adventure
     */
    'country_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Adventure
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Adventure
     */
    'highlights'?: string;
    /**
     * 
     * @type {string}
     * @memberof Adventure
     */
    'testimonial'?: string;
    /**
     * 
     * @type {string}
     * @memberof Adventure
     */
    'client_name'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Adventure
     */
    'slide_ids'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Adventure
     */
    'map_id'?: number;
}
/**
 * Adventure Resource model
 * @export
 * @interface AdventureResource
 */
export interface AdventureResource {
    /**
     * 
     * @type {number}
     * @memberof AdventureResource
     */
    'id'?: number;
    /**
     * 
     * @type {AdventureResourceRegion}
     * @memberof AdventureResource
     */
    'region'?: AdventureResourceRegion;
    /**
     * 
     * @type {string}
     * @memberof AdventureResource
     */
    'country_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdventureResource
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdventureResource
     */
    'highlights'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdventureResource
     */
    'testimonial'?: string;
    /**
     * 
     * @type {string}
     * @memberof AdventureResource
     */
    'client_name'?: string;
    /**
     * 
     * @type {Array<AdventureResourceSlides>}
     * @memberof AdventureResource
     */
    'slides'?: Array<AdventureResourceSlides>;
    /**
     * 
     * @type {AdventureResourceSlides}
     * @memberof AdventureResource
     */
    'map'?: AdventureResourceSlides;
}
/**
 * 
 * @export
 * @interface AdventureResourceRegion
 */
export interface AdventureResourceRegion {
    /**
     * 
     * @type {number}
     * @memberof AdventureResourceRegion
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdventureResourceRegion
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface AdventureResourceSlides
 */
export interface AdventureResourceSlides {
    /**
     * 
     * @type {number}
     * @memberof AdventureResourceSlides
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AdventureResourceSlides
     */
    'url'?: string;
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {Array<AdventureResource>}
     * @memberof InlineResponse200
     */
    'data'?: Array<AdventureResource>;
}
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {AdventureResource}
     * @memberof InlineResponse2001
     */
    'data'?: AdventureResource;
}
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<RegionResource>}
     * @memberof InlineResponse2002
     */
    'data'?: Array<RegionResource>;
}
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {Array<MediaTypeResource>}
     * @memberof InlineResponse2003
     */
    'data'?: Array<MediaTypeResource>;
}
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {MediaTypeResource}
     * @memberof InlineResponse2004
     */
    'data'?: MediaTypeResource;
}
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {RegionResource}
     * @memberof InlineResponse2005
     */
    'data'?: RegionResource;
}
/**
 * Media model
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * 
     * @type {number}
     * @memberof Media
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    'filename'?: string;
    /**
     * 
     * @type {number}
     * @memberof Media
     */
    'media_type_id'?: number;
}
/**
 * MediaType model
 * @export
 * @interface MediaType
 */
export interface MediaType {
    /**
     * 
     * @type {number}
     * @memberof MediaType
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'name'?: string;
}
/**
 * MediaType Resource model
 * @export
 * @interface MediaTypeResource
 */
export interface MediaTypeResource {
    /**
     * 
     * @type {number}
     * @memberof MediaTypeResource
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaTypeResource
     */
    'name'?: string;
}
/**
 * Region model
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    'image'?: string;
}
/**
 * Region Resource model
 * @export
 * @interface RegionResource
 */
export interface RegionResource {
    /**
     * 
     * @type {number}
     * @memberof RegionResource
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegionResource
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegionResource
     */
    'image'?: string;
}
/**
 * Slide model
 * @export
 * @interface Slide
 */
export interface Slide {
    /**
     * 
     * @type {number}
     * @memberof Slide
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Slide
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Slide
     */
    'media_type_id'?: number;
}
/**
 * Subject model
 * @export
 * @interface Subject
 */
export interface Subject {
    /**
     * 
     * @type {number}
     * @memberof Subject
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    'name'?: string;
}

/**
 * AdventureApi - axios parameter creator
 * @export
 */
export const AdventureApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAdventure: async (adventure: Adventure, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adventure' is not null or undefined
            assertParamExists('addAdventure', 'adventure', adventure)
            const localVarPath = `/adventure`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adventure, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adventureList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/adventure`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdventure: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteAdventure', 'id', id)
            const localVarPath = `/adventure/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventure: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAdventure', 'id', id)
            const localVarPath = `/adventure/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureByRegionId: async (regionId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'regionId' is not null or undefined
            assertParamExists('getAdventureByRegionId', 'regionId', regionId)
            const localVarPath = `/adventure/getByRegionId/{regionId}`
                .replace(`{${"regionId"}}`, encodeURIComponent(String(regionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdventure: async (id: number, adventure: Adventure, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAdventure', 'id', id)
            // verify required parameter 'adventure' is not null or undefined
            assertParamExists('updateAdventure', 'adventure', adventure)
            const localVarPath = `/adventure/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adventure, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdventureApi - functional programming interface
 * @export
 */
export const AdventureApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdventureApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAdventure(adventure: Adventure, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Adventure>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAdventure(adventure, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adventureList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adventureList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAdventure(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAdventure(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdventure(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdventure(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdventureByRegionId(regionId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdventureByRegionId(regionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAdventure(id: number, adventure: Adventure, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Adventure>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAdventure(id, adventure, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AdventureApi - factory interface
 * @export
 */
export const AdventureApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdventureApiFp(configuration)
    return {
        /**
         * 
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAdventure(adventure: Adventure, options?: any): AxiosPromise<Adventure> {
            return localVarFp.addAdventure(adventure, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adventureList(options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.adventureList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdventure(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.deleteAdventure(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventure(id: number, options?: any): AxiosPromise<InlineResponse2001> {
            return localVarFp.getAdventure(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureByRegionId(regionId: number, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.getAdventureByRegionId(regionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Adventure ID
         * @param {Adventure} adventure 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdventure(id: number, adventure: Adventure, options?: any): AxiosPromise<Adventure> {
            return localVarFp.updateAdventure(id, adventure, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdventureApi - object-oriented interface
 * @export
 * @class AdventureApi
 * @extends {BaseAPI}
 */
export class AdventureApi extends BaseAPI {
    /**
     * 
     * @param {Adventure} adventure 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public addAdventure(adventure: Adventure, options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).addAdventure(adventure, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public adventureList(options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).adventureList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Adventure ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public deleteAdventure(id: number, options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).deleteAdventure(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Adventure ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public getAdventure(id: number, options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).getAdventure(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} regionId Region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public getAdventureByRegionId(regionId: number, options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).getAdventureByRegionId(regionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Adventure ID
     * @param {Adventure} adventure 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdventureApi
     */
    public updateAdventure(id: number, adventure: Adventure, options?: AxiosRequestConfig) {
        return AdventureApiFp(this.configuration).updateAdventure(id, adventure, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ExodusAPIsApi - axios parameter creator
 * @export
 */
export const ExodusAPIsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} adventureId Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureInfo: async (adventureId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adventureId' is not null or undefined
            assertParamExists('getAdventureInfo', 'adventureId', adventureId)
            const localVarPath = `/exodus/getAdventureInfo/{adventureId}`
                .replace(`{${"adventureId"}}`, encodeURIComponent(String(adventureId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureList: async (regionId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'regionId' is not null or undefined
            assertParamExists('getAdventureList', 'regionId', regionId)
            const localVarPath = `/exodus/getAdventureList/{regionId}`
                .replace(`{${"regionId"}}`, encodeURIComponent(String(regionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegionList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/exodus/getRegionList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExodusAPIsApi - functional programming interface
 * @export
 */
export const ExodusAPIsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExodusAPIsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} adventureId Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdventureInfo(adventureId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdventureInfo(adventureId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdventureList(regionId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdventureList(regionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRegionList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2002>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRegionList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ExodusAPIsApi - factory interface
 * @export
 */
export const ExodusAPIsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExodusAPIsApiFp(configuration)
    return {
        /**
         * 
         * @param {number} adventureId Adventure ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureInfo(adventureId: number, options?: any): AxiosPromise<InlineResponse2001> {
            return localVarFp.getAdventureInfo(adventureId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} regionId Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdventureList(regionId: number, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.getAdventureList(regionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegionList(options?: any): AxiosPromise<InlineResponse2002> {
            return localVarFp.getRegionList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExodusAPIsApi - object-oriented interface
 * @export
 * @class ExodusAPIsApi
 * @extends {BaseAPI}
 */
export class ExodusAPIsApi extends BaseAPI {
    /**
     * 
     * @param {number} adventureId Adventure ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExodusAPIsApi
     */
    public getAdventureInfo(adventureId: number, options?: AxiosRequestConfig) {
        return ExodusAPIsApiFp(this.configuration).getAdventureInfo(adventureId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} regionId Region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExodusAPIsApi
     */
    public getAdventureList(regionId: number, options?: AxiosRequestConfig) {
        return ExodusAPIsApiFp(this.configuration).getAdventureList(regionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExodusAPIsApi
     */
    public getRegionList(options?: AxiosRequestConfig) {
        return ExodusAPIsApiFp(this.configuration).getRegionList(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MediaApi - axios parameter creator
 * @export
 */
export const MediaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _288ae9e127972bc1367d0af34297f27c: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('_288ae9e127972bc1367d0af34297f27c', 'id', id)
            const localVarPath = `/media/deleteMedia/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadMedia: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('downloadMedia', 'id', id)
            const localVarPath = `/media/downloadMedia/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} mediaTypeId 
         * @param {any} file file to upload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadMedia: async (mediaTypeId: number, file: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaTypeId' is not null or undefined
            assertParamExists('uploadMedia', 'mediaTypeId', mediaTypeId)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadMedia', 'file', file)
            const localVarPath = `/media/uploadMedia`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (mediaTypeId !== undefined) { 
                localVarFormParams.append('media_type_id', mediaTypeId as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', new Blob([JSON.stringify(file)], { type: "application/json", }));
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaApi - functional programming interface
 * @export
 */
export const MediaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MediaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async _288ae9e127972bc1367d0af34297f27c(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator._288ae9e127972bc1367d0af34297f27c(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadMedia(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadMedia(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} mediaTypeId 
         * @param {any} file file to upload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadMedia(mediaTypeId: number, file: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Media>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadMedia(mediaTypeId, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MediaApi - factory interface
 * @export
 */
export const MediaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MediaApiFp(configuration)
    return {
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _288ae9e127972bc1367d0af34297f27c(id: number, options?: any): AxiosPromise<any> {
            return localVarFp._288ae9e127972bc1367d0af34297f27c(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Media ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadMedia(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.downloadMedia(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} mediaTypeId 
         * @param {any} file file to upload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadMedia(mediaTypeId: number, file: any, options?: any): AxiosPromise<Media> {
            return localVarFp.uploadMedia(mediaTypeId, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MediaApi - object-oriented interface
 * @export
 * @class MediaApi
 * @extends {BaseAPI}
 */
export class MediaApi extends BaseAPI {
    /**
     * 
     * @param {number} id Media ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public _288ae9e127972bc1367d0af34297f27c(id: number, options?: AxiosRequestConfig) {
        return MediaApiFp(this.configuration)._288ae9e127972bc1367d0af34297f27c(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Media ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public downloadMedia(id: number, options?: AxiosRequestConfig) {
        return MediaApiFp(this.configuration).downloadMedia(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} mediaTypeId 
     * @param {any} file file to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApi
     */
    public uploadMedia(mediaTypeId: number, file: any, options?: AxiosRequestConfig) {
        return MediaApiFp(this.configuration).uploadMedia(mediaTypeId, file, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MediaTypeApi - axios parameter creator
 * @export
 */
export const MediaTypeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _0df5be1eea3e1425a62af192ccf1a514: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mediatype`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        b1a66a80eeeaf7177f395b0f3652e457: async (id: number, mediaType: MediaType, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('b1a66a80eeeaf7177f395b0f3652e457', 'id', id)
            // verify required parameter 'mediaType' is not null or undefined
            assertParamExists('b1a66a80eeeaf7177f395b0f3652e457', 'mediaType', mediaType)
            const localVarPath = `/mediatype/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mediaType, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cecdbcc2202fc94e01edcf61f8f89119: async (mediaType: MediaType, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaType' is not null or undefined
            assertParamExists('cecdbcc2202fc94e01edcf61f8f89119', 'mediaType', mediaType)
            const localVarPath = `/mediatype`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mediaType, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        e38550531275a28f7911f967a9bdd3f9: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('e38550531275a28f7911f967a9bdd3f9', 'id', id)
            const localVarPath = `/mediatype/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ebb7786f5d04ac4384dd799a77052087: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ebb7786f5d04ac4384dd799a77052087', 'id', id)
            const localVarPath = `/mediatype/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaTypeApi - functional programming interface
 * @export
 */
export const MediaTypeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MediaTypeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async _0df5be1eea3e1425a62af192ccf1a514(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2003>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator._0df5be1eea3e1425a62af192ccf1a514(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async b1a66a80eeeaf7177f395b0f3652e457(id: number, mediaType: MediaType, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MediaType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.b1a66a80eeeaf7177f395b0f3652e457(id, mediaType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cecdbcc2202fc94e01edcf61f8f89119(mediaType: MediaType, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MediaType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cecdbcc2202fc94e01edcf61f8f89119(mediaType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async e38550531275a28f7911f967a9bdd3f9(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.e38550531275a28f7911f967a9bdd3f9(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ebb7786f5d04ac4384dd799a77052087(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2004>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ebb7786f5d04ac4384dd799a77052087(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MediaTypeApi - factory interface
 * @export
 */
export const MediaTypeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MediaTypeApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _0df5be1eea3e1425a62af192ccf1a514(options?: any): AxiosPromise<InlineResponse2003> {
            return localVarFp._0df5be1eea3e1425a62af192ccf1a514(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        b1a66a80eeeaf7177f395b0f3652e457(id: number, mediaType: MediaType, options?: any): AxiosPromise<MediaType> {
            return localVarFp.b1a66a80eeeaf7177f395b0f3652e457(id, mediaType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {MediaType} mediaType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cecdbcc2202fc94e01edcf61f8f89119(mediaType: MediaType, options?: any): AxiosPromise<MediaType> {
            return localVarFp.cecdbcc2202fc94e01edcf61f8f89119(mediaType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        e38550531275a28f7911f967a9bdd3f9(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.e38550531275a28f7911f967a9bdd3f9(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Media Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ebb7786f5d04ac4384dd799a77052087(id: number, options?: any): AxiosPromise<InlineResponse2004> {
            return localVarFp.ebb7786f5d04ac4384dd799a77052087(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MediaTypeApi - object-oriented interface
 * @export
 * @class MediaTypeApi
 * @extends {BaseAPI}
 */
export class MediaTypeApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTypeApi
     */
    public _0df5be1eea3e1425a62af192ccf1a514(options?: AxiosRequestConfig) {
        return MediaTypeApiFp(this.configuration)._0df5be1eea3e1425a62af192ccf1a514(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Media Type ID
     * @param {MediaType} mediaType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTypeApi
     */
    public b1a66a80eeeaf7177f395b0f3652e457(id: number, mediaType: MediaType, options?: AxiosRequestConfig) {
        return MediaTypeApiFp(this.configuration).b1a66a80eeeaf7177f395b0f3652e457(id, mediaType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {MediaType} mediaType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTypeApi
     */
    public cecdbcc2202fc94e01edcf61f8f89119(mediaType: MediaType, options?: AxiosRequestConfig) {
        return MediaTypeApiFp(this.configuration).cecdbcc2202fc94e01edcf61f8f89119(mediaType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Media Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTypeApi
     */
    public e38550531275a28f7911f967a9bdd3f9(id: number, options?: AxiosRequestConfig) {
        return MediaTypeApiFp(this.configuration).e38550531275a28f7911f967a9bdd3f9(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Media Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTypeApi
     */
    public ebb7786f5d04ac4384dd799a77052087(id: number, options?: AxiosRequestConfig) {
        return MediaTypeApiFp(this.configuration).ebb7786f5d04ac4384dd799a77052087(id, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RegionApi - axios parameter creator
 * @export
 */
export const RegionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRegion: async (region: Region, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'region' is not null or undefined
            assertParamExists('addRegion', 'region', region)
            const localVarPath = `/region`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(region, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRegion: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRegion', 'id', id)
            const localVarPath = `/region/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegion: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRegion', 'id', id)
            const localVarPath = `/region/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/region`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRegion: async (id: number, region: Region, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRegion', 'id', id)
            // verify required parameter 'region' is not null or undefined
            assertParamExists('updateRegion', 'region', region)
            const localVarPath = `/region/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(region, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegionApi - functional programming interface
 * @export
 */
export const RegionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RegionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addRegion(region: Region, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Region>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addRegion(region, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRegion(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRegion(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRegion(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2005>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRegion(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2002>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRegion(id: number, region: Region, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Region>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRegion(id, region, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RegionApi - factory interface
 * @export
 */
export const RegionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RegionApiFp(configuration)
    return {
        /**
         * 
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRegion(region: Region, options?: any): AxiosPromise<Region> {
            return localVarFp.addRegion(region, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRegion(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.deleteRegion(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRegion(id: number, options?: any): AxiosPromise<InlineResponse2005> {
            return localVarFp.getRegion(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionList(options?: any): AxiosPromise<InlineResponse2002> {
            return localVarFp.regionList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id Region ID
         * @param {Region} region 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRegion(id: number, region: Region, options?: any): AxiosPromise<Region> {
            return localVarFp.updateRegion(id, region, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RegionApi - object-oriented interface
 * @export
 * @class RegionApi
 * @extends {BaseAPI}
 */
export class RegionApi extends BaseAPI {
    /**
     * 
     * @param {Region} region 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public addRegion(region: Region, options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).addRegion(region, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public deleteRegion(id: number, options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).deleteRegion(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Region ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public getRegion(id: number, options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).getRegion(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public regionList(options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).regionList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id Region ID
     * @param {Region} region 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public updateRegion(id: number, region: Region, options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).updateRegion(id, region, options).then((request) => request(this.axios, this.basePath));
    }
}


